"""
Exact / near-exact per-film posterior inference.

Given fitted type priors, films factorize once the shared observation noise
`σ_obs` is fixed or marginalized. For fixed decay `η = logit(d)` and `σ_obs`,
`logO` has a conjugate Gaussian posterior and an analytic marginal evidence.

Downstream rankings still require Monte Carlo over composed gross draws.
"""

# ---------------------------------------------------------------------------
# Stable curve primitives (also Wasm-safe)
# ---------------------------------------------------------------------------

"""Opening-to-cumulative multiplier at run-week `t` for retention `d`."""
function curve_factor(d::Float64, t::Float64)::Float64
    t <= 0 && return 0.0
    if abs(d - 1.0) < 1e-12
        return t
    end
    # (1 - d^t) / (1 - d) via expm1 for stability near d≈1
    return -expm1(t * log(d)) / (1 - d)
end

"""Interval gross multiplier from run-week `t0` to `t1` (non-overlapping)."""
function interval_factor(d::Float64, t0::Float64, t1::Float64)::Float64
    t1 <= t0 && return 0.0
    return curve_factor(d, t1) - curve_factor(d, t0)
end

"""Remaining-gross multiplier from banked pin time to cutoff."""
function remaining_factor(d::Float64, t_pin::Float64, t_cut::Float64)::Float64
    # G = banked * (1 + (d^{t_pin} - d^{t_cut}) / (1 - d^{t_pin}))
    # remaining / banked = (d^{t_pin} - d^{t_cut}) / (1 - d^{t_pin})
    t_cut <= t_pin && return 0.0
    d = clamp(d, 1e-9, 1 - 1e-9)
    num = exp(t_pin * log(d)) - exp(t_cut * log(d))
    den = 1 - exp(t_pin * log(d))
    den <= 0 && return 0.0
    return max(num / den, 0.0)
end

logistic(x::Float64) = 1 / (1 + exp(-x))
# logit is defined in model.jl

# Interval observations come from `interval_observations` in data.jl:
# NamedTuple (film, t_start, t_end, interval_gross, theaters_end).

# ---------------------------------------------------------------------------
# Analytic logO conditional + evidence (fixed η, σ)
# ---------------------------------------------------------------------------

"""
For fixed decay `d` and noise `σ`, compute the marginal evidence for interval
observations and the posterior of `logO`.

Each interval contributes:
    log(ΔC) = logO + log(interval_factor(d, t_start, t_end)) + ε,  ε ~ N(0, σ²)

Returns `(log_evidence, post_mean, post_std)`.
"""
function logO_posterior(
    intervals,
    d::Float64,
    σ::Float64,
    μ_logO::Float64,
    σ_logO::Float64,
)
    σ = max(σ, 1e-6)
    σ_logO = max(σ_logO, 1e-6)
    zs = Float64[]
    for iv in intervals
        f = interval_factor(d, Float64(iv.t_start), Float64(iv.t_end))
        f > 0 || continue
        iv.interval_gross > 0 || continue
        push!(zs, log(Float64(iv.interval_gross)) - log(f))
    end
    K = length(zs)
    if K == 0
        # No observations → prior is posterior; evidence = 1
        return (0.0, μ_logO, σ_logO)
    end
    τ2 = σ_logO^2
    σ2 = σ^2
    # Posterior precision / mean
    prec = 1 / τ2 + K / σ2
    post_var = 1 / prec
    post_mean = post_var * (μ_logO / τ2 + sum(zs) / σ2)
    post_std = sqrt(post_var)
    # Marginal evidence: z ~ N(μ 1, σ²I + τ² 11ᵀ)
    r = zs .- μ_logO
    Q = sum(abs2, r)
    S = sum(r)
    logdet = K * log(σ2) + log1p(K * τ2 / σ2)
    quad = Q / σ2 - (τ2 / (σ2 * (σ2 + K * τ2))) * S * S
    logZ = -0.5 * (K * log(2π) + logdet + quad)
    return (logZ, post_mean, post_std)
end

# ---------------------------------------------------------------------------
# Quadrature nodes (precomputed low-order Gauss–Hermite / Legendre)
# ---------------------------------------------------------------------------

# 16-point Gauss–Hermite nodes/weights for ∫ f(x) e^{-x²} dx
const GH_NODES_16 = Float64[
    -4.688738939305818,
    -3.869447904860123,
    -3.176999161979956,
    -2.546202157847481,
    -1.951787990716324,
    -1.380258895201282,
    -0.822951449144656,
    -0.273444895157662,
     0.273444895157662,
     0.822951449144656,
     1.380258895201282,
     1.951787990716324,
     2.546202157847481,
     3.176999161979956,
     3.869447904860123,
     4.688738939305818,
]
const GH_WEIGHTS_16 = Float64[
    2.654948647467865e-10,
    2.320980773852886e-7,
    2.711860092537882e-5,
    0.000932068658579142,
    0.0128805775447012,
    0.083810041487892,
    0.280619092494332,
    0.507431899351916,
    0.507431899351916,
    0.280619092494332,
    0.083810041487892,
    0.0128805775447012,
    0.000932068658579142,
    2.711860092537882e-5,
    2.320980773852886e-7,
    2.654948647467865e-10,
]

# 32-point Gauss–Legendre on [-1,1]
function _gl32()
    # Use a compact 16-point Legendre set first (good enough + doubles via symmetry).
    # Full 32 generated by Golub-Welsch would be longer; ship verified 16 then upsample.
    x16 = Float64[
        -0.9894009349916499,
        -0.9445750230732326,
        -0.8656312023878318,
        -0.7554044083550030,
        -0.6178762444026438,
        -0.4580167776572274,
        -0.2816035507792589,
        -0.0950125098376374,
         0.0950125098376374,
         0.2816035507792589,
         0.4580167776572274,
         0.6178762444026438,
         0.7554044083550030,
         0.8656312023878318,
         0.9445750230732326,
         0.9894009349916499,
    ]
    w16 = Float64[
        0.0271524594117541,
        0.0622535239386479,
        0.0951585116824928,
        0.1246289712555339,
        0.1495959888165767,
        0.1691565193950025,
        0.1826034150449236,
        0.1894506104550685,
        0.1894506104550685,
        0.1826034150449236,
        0.1691565193950025,
        0.1495959888165767,
        0.1246289712555339,
        0.0951585116824928,
        0.0622535239386479,
        0.0271524594117541,
    ]
    return x16, w16
end

const GL_NODES_16, GL_WEIGHTS_16 = _gl32()

"""Map Gauss–Hermite nodes for η ~ N(μ, σ²): η = μ + √2 σ x, weight *= √π⁻¹ factor handled via w*π^{-1/2}."""
function hermite_nodes(μ::Float64, σ::Float64; order::Int = 16)
    xs = GH_NODES_16
    ws = GH_WEIGHTS_16
    n = min(order, length(xs))
    # ∫ f(η) N(η;μ,σ) dη = ∫ f(μ+√2 σ x) * w(x) / √π  dx  where w are GH weights for e^{-x²}
    inv_sqrt_pi = 1 / sqrt(π)
    nodes = Vector{Float64}(undef, n)
    weights = Vector{Float64}(undef, n)
    for i in 1:n
        nodes[i] = μ + sqrt(2) * σ * xs[i]
        weights[i] = ws[i] * inv_sqrt_pi
    end
    return nodes, weights
end

"""Gauss–Legendre nodes on truncated σ ∈ [lo, hi] with truncated-normal prior density later."""
function legendre_nodes(lo::Float64, hi::Float64; order::Int = 16)
    xs = GL_NODES_16
    ws = GL_WEIGHTS_16
    n = min(order, length(xs))
    nodes = Vector{Float64}(undef, n)
    weights = Vector{Float64}(undef, n)
    mid = 0.5 * (hi + lo)
    half = 0.5 * (hi - lo)
    for i in 1:n
        nodes[i] = mid + half * xs[i]
        weights[i] = ws[i] * half
    end
    return nodes, weights
end

"""Unnormalized truncated-normal log-density on [lo,hi] (normalization handled across grid)."""
function log_trunc_normal(x::Float64, μ::Float64, σ::Float64)
    z = (x - μ) / σ
    return -0.5 * z * z - log(σ) - 0.5 * log(2π)
end

# ---------------------------------------------------------------------------
# Theater-tail soft observation
# ---------------------------------------------------------------------------

"""
Calibrated remaining-gross prior from exhibition state.

When theaters are very low and PTA is weak, remaining upside collapses.
Returns an optional soft observation on `log(remaining)` ≈ logO + log(remaining_factor).
"""
function theater_tail_observation(
    banked::Float64,
    theaters::Union{Missing,Int},
    t_now::Float64,
    t_cut::Float64;
    pta::Union{Missing,Float64} = missing,
)
    (banked > 0 && t_cut > t_now && t_now > 0) || return nothing
    th = theaters isa Missing ? 2000 : Int(theaters)
    # Expected remaining weeks of meaningful exhibition
    if th <= 50
        remaining_weeks = 0.5
        σ_tail = 0.25
    elseif th <= 200
        remaining_weeks = 1.0
        σ_tail = 0.35
    elseif th <= 500
        remaining_weeks = 1.5
        σ_tail = 0.45
    else
        return nothing  # still wide — no extra constraint
    end
    weekly = if pta isa Missing
        # Rough: banked/t_now as average weekly, scaled by theater share vs wide (~3500)
        (banked / max(t_now, 1.0)) * (th / 3500)
    else
        Float64(pta) * th
    end
    expected_remaining = max(weekly * remaining_weeks, 1.0)
    return (log_remaining = log(expected_remaining), σ = σ_tail)
end

# ---------------------------------------------------------------------------
# Per-film quadrature posterior over η | σ
# ---------------------------------------------------------------------------

struct FilmPrior
    title::String
    μ_logO::Float64
    σ_logO::Float64
    μ_logit_d::Float64
    σ_logit_d::Float64
    t_cut::Float64
    banked::Float64
    t_now::Float64
    theaters::Union{Missing,Int}
    released::Bool
end

"""
For one film and fixed σ, return discrete posterior over Hermite η-nodes:
`(η_nodes, weights_normalized, logO_mean_per_node, logO_std_per_node, log_evidence)`.
"""
function film_eta_posterior(
    prior::FilmPrior,
    intervals,
    σ::Float64;
    order::Int = 16,
)
    ηs, w0 = hermite_nodes(prior.μ_logit_d, prior.σ_logit_d; order)
    n = length(ηs)
    logw = fill(-Inf, n)
    μO = Vector{Float64}(undef, n)
    σO = Vector{Float64}(undef, n)
    film_iv = filter(iv -> iv.film == prior.title, intervals)
    for i in 1:n
        d = clamp(logistic(ηs[i]), 1e-6, 1 - 1e-6)
        logZ, m, s = logO_posterior(film_iv, d, σ, prior.μ_logO, prior.σ_logO)
        # Optional theater-tail soft observation on remaining
        tail = theater_tail_observation(prior.banked, prior.theaters, prior.t_now, prior.t_cut)
        if tail !== nothing && prior.banked > 0
            # remaining = banked * remaining_factor(d, t_pin, t_cut)
            # so log(remaining) = log(banked) + log(rf)  — independent of logO when pinned
            # Use as soft check on decay instead: predicted remaining vs observed expectation
            t_pin = max(prior.t_now, 1.0)
            rf = remaining_factor(d, t_pin, prior.t_cut)
            pred = prior.banked * rf
            if pred > 0
                resid = log(pred) - tail.log_remaining
                logZ -= 0.5 * (resid / tail.σ)^2 + log(tail.σ) + 0.5 * log(2π)
            end
        end
        logw[i] = log(w0[i]) + logZ
        μO[i] = m
        σO[i] = s
    end
    mlog = maximum(logw)
    w = exp.(logw .- mlog)
    Z = sum(w)
    w ./= Z
    log_evidence = mlog + log(Z)
    return (ηs = ηs, w = w, μO = μO, σO = σO, log_evidence = log_evidence)
end

# ---------------------------------------------------------------------------
# Shared σ marginalization + joint sampling
# ---------------------------------------------------------------------------

struct InferenceConfig
    σ_lo::Float64
    σ_hi::Float64
    σ_prior_μ::Float64
    σ_prior_σ::Float64
    η_order::Int
    σ_order::Int
end

const DEFAULT_INFERENCE = InferenceConfig(0.02, 1.0, 0.15, 0.1, 16, 16)

"""
Build the discrete posterior over σ nodes by multiplying per-film evidences
with the truncated-normal prior.
"""
function sigma_posterior(
    priors::AbstractVector{FilmPrior},
    intervals,
    cfg::InferenceConfig = DEFAULT_INFERENCE,
)
    σs, wσ = legendre_nodes(cfg.σ_lo, cfg.σ_hi; order = cfg.σ_order)
    nσ = length(σs)
    logp = Vector{Float64}(undef, nσ)
    # Cache per (film, σ-index) eta posteriors
    cache = Dict{Tuple{Int,Int},Any}()
    for (j, σ) in enumerate(σs)
        lp = log_trunc_normal(σ, cfg.σ_prior_μ, cfg.σ_prior_σ) + log(wσ[j])
        for (fi, pr) in enumerate(priors)
            if !pr.released
                continue  # unreleased: evidence = 1 (prior only)
            end
            post = film_eta_posterior(pr, intervals, σ; order = cfg.η_order)
            cache[(fi, j)] = post
            lp += post.log_evidence
        end
        logp[j] = lp
    end
    m = maximum(logp)
    w = exp.(logp .- m)
    w ./= sum(w)
    return (σs, w, cache)
end

"""
Draw `n_draws` season-gross matrices using quadrature posterior + exact conditionals.

Returns `G` (films × draws), plus diagnostic NamedTuple.
"""
function sample_factored_grosses(
    priors::AbstractVector{FilmPrior},
    intervals,
    n_draws::Int;
    cfg::InferenceConfig = DEFAULT_INFERENCE,
    seed::Int = 42,
    overrides::Dict{String,Float64} = Dict{String,Float64}(),  # title => opening $M
)
    Random.seed!(seed)
    σs, wσ, cache = sigma_posterior(priors, intervals, cfg)
    n_films = length(priors)
    G = Matrix{Float64}(undef, n_films, n_draws)
    # Precompute CDF for σ
    cdf_σ = cumsum(wσ)
    for draw in 1:n_draws
        # Sample shared σ
        u = rand()
        jσ = searchsortedfirst(cdf_σ, u)
        jσ = clamp(jσ, 1, length(σs))
        σ = σs[jσ]
        for (fi, pr) in enumerate(priors)
            # Opening override shifts μ_logO for controlled unreleased films
            μ_logO = pr.μ_logO
            σ_logO = pr.σ_logO
            if haskey(overrides, pr.title)
                μ_logO = log(overrides[pr.title] * 1e6)
                # keep film's σ_logO (caller may pass tighter)
            end
            if !pr.released
                # Exact prior draw
                logO = μ_logO + σ_logO * randn()
                η = pr.μ_logit_d + pr.σ_logit_d * randn()
                d = clamp(logistic(η), 1e-6, 1 - 1e-6)
                O = exp(logO)
                G[fi, draw] = cumulative_gross(O, d, pr.t_cut)
                continue
            end
            key = (fi, jσ)
            if !haskey(cache, key)
                # Recompute with possibly overridden prior means — rare for released
                pr2 = FilmPrior(
                    pr.title, μ_logO, σ_logO, pr.μ_logit_d, pr.σ_logit_d,
                    pr.t_cut, pr.banked, pr.t_now, pr.theaters, pr.released,
                )
                cache[key] = film_eta_posterior(pr2, intervals, σ; order = cfg.η_order)
            end
            ηs, wη, μO, σO = cache[key].ηs, cache[key].w, cache[key].μO, cache[key].σO
            # Sample η node
            cdf = cumsum(wη)
            k = searchsortedfirst(cdf, rand())
            k = clamp(k, 1, length(ηs))
            η = ηs[k]
            d = clamp(logistic(η), 1e-6, 1 - 1e-6)
            logO = μO[k] + σO[k] * randn()
            O = exp(logO)
            G[fi, draw] = season_total(O, d, pr.t_cut; banked = pr.banked, t_now = pr.t_now)
        end
    end
    return G, (; σs, wσ, n_draws, seed, cfg)
end

# ---------------------------------------------------------------------------
# Rank-distance representative winning world
# ---------------------------------------------------------------------------

"""Kendall-tau style distance between two Top-10 title lists (positions matter)."""
function rank_list_distance(a::AbstractVector{<:AbstractString}, b::AbstractVector{<:AbstractString})
    pos_b = Dict(t => i for (i, t) in enumerate(b))
    dist = 0.0
    for (i, t) in enumerate(a)
        j = get(pos_b, t, length(b) + 2)
        dist += abs(i - j)
    end
    # Penalize titles in b missing from a
    set_a = Set(a)
    for (j, t) in enumerate(b)
        if !(t in set_a)
            dist += abs(j - (length(a) + 2))
        end
    end
    return dist
end

"""
Among draws where `player` wins (sole or tied), pick the draw whose Top-10 is
nearest the coordinate-wise consensus ranking (modal/median position proxy:
ranking from median grosses among win draws).
"""
function representative_win_draw(
    titles::Vector{String},
    G::Matrix{Float64},
    win_draw_indices::Vector{Int};
    top_n::Int = 10,
)
    isempty(win_draw_indices) && return nothing
    n_films = size(G, 1)
    medG = [median(@view G[i, win_draw_indices]) for i in 1:n_films]
    consensus = rank_by_gross(titles, medG; n = top_n)
    best = win_draw_indices[1]
    best_d = Inf
    for j in win_draw_indices
        ranking = rank_by_gross(titles, @view(G[:, j]); n = top_n)
        d = rank_list_distance(ranking, consensus)
        if d < best_d
            best_d = d
            best = j
        end
    end
    return best
end

"""Build `FilmPrior` vector from season data + fitted type priors."""
function film_priors_from_season(season::SeasonData, type_priors::AbstractDict)
    floors = observed_floors(season)
    times = observed_times(season)
    priors = FilmPrior[]
    for f in season.films
        t_cut = t_cutoff(f.release_date)
        banked = get(floors, f.title, 0.0)
        t_now = get(times, f.title, 0.0)
        # Latest theaters from observations
        theaters = missing
        for o in season.observations
            if o.film == f.title && (theaters isa Missing || o.t >= t_now - 1e-9)
                theaters = o.theaters
            end
        end
        if f.released
            p = prior_for(f.type, type_priors)
            μ_logO = Float64(p.μ_logO)
            σ_logO = Float64(p.σ_logO)
            # Synthetic EB history often collapses unknown types to pooled long legs.
            # Prefer the curated type decay table when this type wasn't actually fit.
            if !haskey(type_priors, f.type) && haskey(UNRELEASED_DECAY_D, f.type)
                d = clamp(UNRELEASED_DECAY_D[f.type], 0.05, 0.95)
                μ_logit_d = logit(d)
                σ_logit_d = UNRELEASED_LOGIT_D_STD
            else
                μ_logit_d = Float64(p.μ_logit_d)
                σ_logit_d = Float64(p.σ_logit_d)
            end
        else
            up = unreleased_prior(f)
            μ_logO = up.μ_logO
            σ_logO = up.σ_logO
            μ_logit_d = up.μ_logit_d
            σ_logit_d = up.σ_logit_d
        end
        push!(
            priors,
            FilmPrior(
                f.title,
                μ_logO,
                σ_logO,
                μ_logit_d,
                σ_logit_d,
                t_cut,
                banked,
                t_now,
                theaters,
                f.released,
            ),
        )
    end
    return priors
end
